<?xml version="1.0" encoding="utf-8" ?>
<project name="jenkins" default="war" basedir=".">
    <property name="jboss.deploy.dir" value="D:/wildfly-8.2.1.Final/standalone/deployments" />   
    <target name="war" description="Create a war file">
        <zip destfile="jenkins.war" basedir="dist/jenkins"/>
        <copy todir="${jboss.deploy.dir}">
            <fileset dir="." includes="jenkins.war"/>
        </copy>
    </target>
</project>   